### ISSUE TITLE
Multi-repo / multi-project support

### ISSUE THREAD

**Issue by richardolsson** [zetkin/lyra#16]

**Comment by amerharb** [comment]
can we say that we closed this issue?

**Comment by richardolsson** [comment]
I think so! In the future, I recommend putting "Resolves #16" in a PR that solves an issue like this.

On that same note, I would like to start naming the branch for an issue as `issue-N/some-label` where `N` is the number of the issue (16 in this case) and `some-label` is some arbitrary but descriptive slug-like string, e.g. `multi-project-support`, so the full name becomes (`issue-16/multi-project-support`). That is inline with the Zetkin contributor guidelines.

If a branch is not related to an issue, we call them `undocumented/multi-project-support` instead.
