### ISSUE TITLE
Project page with language list

### ISSUE THREAD

**Issue by richardolsson** [zetkin/lyra#20]

**Comment by amerharb** [comment]
do we need first to define the supported language in lyra.yml file? either for all repo for each project.

**Comment by richardolsson** [comment]
Yeah, I agree that's a good first step @amerharb!

**Comment by WULCAN** [comment]
A project page with a list of languages was designed in https://github.com/zetkin/lyra/issues/75 and implemented in https://github.com/zetkin/lyra/pull/92
