### ISSUE TITLE
Handle multiple YML files for translations when writing

### ISSUE THREAD

**Issue by richardolsson** [zetkin/lyra#29]
The `YamlTranslationAdapter` correctly reads from multiple files, but the same needs to work when writing back to disk before committing. This logic currently lives elsewhere (in the pull request API endpoint) which always just writes to a single file.

**Comment by WULCAN** [comment]
Even if multiple YML files are arguably not MVP, at least writing back to the original file instead of to a hard coded file is part of MVP. I think that is one of the things we are resolving in the pull requests for this issue.

**Comment by WULCAN** [comment]
This was resolved in #130
