### ISSUE TITLE
Project Card

### ISSUE THREAD

**Issue by Bagera** [zetkin/lyra#74]
## Description

A project card should link to the project page. The language buttons should link to the specific translation page for that language.

## Design Specification

![image](https://github.com/zetkin/lyra/assets/2950171/a01b8671-959f-444c-a67a-75de595a1cd8)
Fig. 1: A project with a list of languages. Languages should be equal size in 3 columns. Message count and language progress is not part of the MVP but reflects a possible future.

![image](https://github.com/zetkin/lyra/assets/2950171/801ed540-411e-4738-b4f0-a1cd3bc10e81)
Fig. 2: Active/Hover state

**Comment by henrycatalinismith** [comment]
Working on this a bit tonight.

**Comment by WULCAN** [comment]
The contrast between the project card and the page background is very low on cheap screens. The design for the project page also has low contrast between language card and page background.

Would it be a problem if we change the card background to something darker?
