### ISSUE TITLE
Language card

### ISSUE THREAD

**Issue by Bagera** [zetkin/lyra#76]
## Description

A language card should link to the appropriate translation.

Statistics and progress bar are not part of the MVP.

## Design Specification

![image](https://github.com/zetkin/lyra/assets/2950171/ddfcd524-fb85-45b6-bc27-4d640a419942)
Fig. 1: Language card in default state.

![image](https://github.com/zetkin/lyra/assets/2950171/db4991a9-6edf-49c7-8e5f-cc265e308aad)
Fig. 2: Active/Hover state.

**Comment by henrycatalinismith** [comment]
https://github.com/zetkin/lyra/pull/92 implemented this.
