### ISSUE TITLE
Title bar

### ISSUE THREAD

**Issue by Bagera** [zetkin/lyra#77]
## Description

The translation page should have a title bar with a link to the home page, a link to the current project and the abbreviation of the translation language.

## Design specifications

![image](https://github.com/zetkin/lyra/assets/2950171/3587570e-50e9-4bb8-acd6-60ba0e853504)
Fig. 1: Title bar

**Comment by henrycatalinismith** [comment]
https://github.com/zetkin/lyra/pull/107 actually covered this 100% as far as I can tell!!
